version: '3.8'

services:
  cd-server:
    build:
      context: ./cd-server
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis

  redis:
    image: redis:latest

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  tester:
    build:
      context: ./tester
    depends_on:
      - cd-server
    entrypoint: ["pytest"]